version: '3'
services:
  app:
    build: .
    networks:
      - ctfnet
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.insomnia.entrypoints=web"
      - "traefik.http.routers.insomnia.rule=Host(`insomnia.game.alcapwnctf.in`)"
      - "traefik.http.services.insomnia.loadbalancer.server.port=8888"

networks:
  ctfnet:
      name: challenge_net
      external: true
  internal:
    
